version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
    - '4200:4200'
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
    - '5000:5000'
  microservicio:
    build:
      context: ./microservicio
      dockerfile: Dockerfile
    ports:
    - '2500:2500'