FROM node:latest as node

WORKDIR /app

COPY package*.json ./
COPY . .

RUN npm install
RUN npm run build

FROM nginx:latest

COPY --from=node /app/dist/frontend /usr/share/nginx/html

EXPOSE 4200/

RUN sed -i 's/listen\(.*\)80;/listen 4200;/' /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]